apiVersion: v1
kind: Namespace
metadata:
  name:  frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: custody-service
  namespace: backend
  labels:
    tipo: microservicio
    app: custody-service-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      tipo: microservicio
      app: custody-service-backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        tipo: microservicio
        app: custody-service-backend
    spec:
      containers:
      - name: custody-service
        image: custody-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name : grpc
          containerPort: 5000
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: custody-service
  namespace: backend
  labels:
    tipo: microservicio
    app: custody-service-backend
spec:
  ports:
  - name: grpc
    protocol: TCP
    port: 5000
    targetPort: 5000
  selector:
    tipo: microservicios
    app: custody-service-backend
  type: ClusterIP